apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-west4-docker.pkg.dev/terraform-learning-503012/my-repository/hello-cloudbuild-dev:v3.0
        ports:
        - containerPort: 8080
