steps:
# 1. הרצת בדיקות יוניט
- name: 'python:3.7-slim'
  id: Test
  dir: 'gke-gitops-cloudbuild/hello-cloudbuild-app'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# 2. בניית ה-Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  dir: 'gke-gitops-cloudbuild/hello-cloudbuild-app'
  args:
  - 'build'
  - '-t'
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA'
  - '.'

# 3. דחיפה ל-Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY