steps:
# 1. הרצת בדיקות יוניט (בגלל שהוא כבר בתיקייה, פשוט מריצים)
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# 2. בניית ה-Docker Image מתוך התיקייה הנוכחית (נקודה בסוף)
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA'
  - '.'
# 3. דחיפה ל-Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:$SHORT_SHA'

# 4. הגדרת מפתח ה-SSH מתוך Secret Manager
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# 5. שיבוט ה-Repository של ה-Env
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:liorG1/gcp-devops-certification.git
  volumes:
  - name: ssh
    path: /root/.ssh

# 6. מעבר לבראנץ' המתאים ועדכון המניפסט
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd gcp-devops-certification
    git config user.email "$(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
    git config user.name "Cloud Build"
    # ייצור המניפסט החדש עם ה-Tag המעודכן לתוך התיקייה הרלוונטית
    sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" ../hello-cloudbuild-env/kubernetes.yaml.tpl | \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > gke-gitops-cloudbuild/hello-cloudbuild-env/kubernetes.yaml
    
    git add gke-gitops-cloudbuild/hello-cloudbuild-env/kubernetes.yaml
    git commit -m "Deploying image hello-cloudbuild:${SHORT_SHA} from app commit ${COMMIT_SHA}"
    git push origin main
  volumes:
  - name: ssh
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/terraform-learning-503012/secrets/ssh_key_secret/versions/1
    env: 'SSH_KEY'

options:
  logging: CLOUD_LOGGING_ONLY