steps:
# Step 0: Run Unit Tests
- name: 'python:3.7-slim'
  id: 'Test'
  dir: 'gke-pipeline-cloudbuild-lab/hello-cloudbuild-app'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install flask
    python -m unittest test_app.py

# Step 1: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  dir: 'gke-pipeline-cloudbuild-lab/hello-cloudbuild-app'
  args: ['build', '-t', 'us-west4-docker.pkg.dev/terraform-learning-503012/my-repository/hello-cloudbuild:$SHORT_SHA', '.']

# Step 2: Push Docker Image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  dir: 'gke-pipeline-cloudbuild-lab/hello-cloudbuild-app'
  args: ['push', 'us-west4-docker.pkg.dev/terraform-learning-503012/my-repository/hello-cloudbuild:$SHORT_SHA']

# Step 3: Clone the Env Repo using Git
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone Env Repo'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mkdir -p /root/.ssh
    echo "-----BEGIN OPENSSH PRIVATE KEY-----
    מפתח_כאן
    -----END OPENSSH PRIVATE KEY-----" > /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
    git clone git@github.com:liorG1/gcp-devops-certification.git

options:
  logging: CLOUD_LOGGING_ONLY